(()=>{const token=document.querySelector('meta[name="yfl-token"]').content,$=s=>document.querySelector(s);let state,selected=0,dirty=false,timer;
async function api(path,method='GET',body){const o={method,headers:{'X-YFL-Token':token}};if(body){o.headers['Content-Type']='application/json';o.body=JSON.stringify(body)}const r=await fetch(path,o),d=await r.json().catch(()=>({error:'Bad server response'}));if(!r.ok){const e=new Error(d.error||'Request failed');e.status=r.status;throw e}return d}
const fmt=s=>`${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`;
function nav(){const n=$('#nav');n.textContent='';state.problems.forEach((p,i)=>{const b=document.createElement('button');b.className='navbtn'+(i===selected?' active':'')+(p.passed?' pass':'');b.textContent=`${p.passed?'✓ ':''}Problem ${i+1} · ${p.difficulty}`;b.onclick=async()=>{if(dirty)await save(false);selected=i;await api('/api/select','POST',{index:i}).catch(()=>{});problem()};n.appendChild(b)})}
function result(r){const e=$('#result');e.className='';if(!r){e.textContent='Write your Python solution and hit Run.';return}if(r.kind==='saved'){e.textContent=r.message;return}if(r.compile&&!r.compile.ok){e.className='bad';e.textContent=`Compile error${r.compile.line?' on line '+r.compile.line:''}: ${r.compile.message}${r.compile.text?'\n'+r.compile.text:''}`;return}if(r.ok){e.className='good';e.textContent='✓ Python compiled successfully\n✓ All randomized hidden tests passed';return}e.className='bad';e.textContent='✓ Python compiled successfully\n✗ Hidden tests failed or raised an error'}
function problem(){const p=state.problems[selected];$('#difficulty').textContent=p.difficulty;$('#title').textContent=`Problem ${selected+1} of 5`;$('#prompt').textContent=p.prompt;$('#function').textContent=p.function+'(*args)';$('#code').value=p.code;dirty=false;$('#saveState').textContent='Saved on disk';const ex=$('#examples');ex.textContent='';p.examples.forEach((x,i)=>{const q=document.createElement('pre');q.className='example';q.textContent=`Example ${i+1}\nargs = ${JSON.stringify(x.args)}\nexpected = ${JSON.stringify(x.expected)}`;ex.appendChild(q)});result(p.lastResult);nav()}
function header(){const c=state.complete;$('#summary').textContent=`${c}/5 passed · code and progress survive browser/tab/window changes for 60 minutes`;$('#bar').style.width=`${c*20}%`;$('#finish').hidden=c!==5}
function expire(){clearInterval(timer);$('#app').hidden=true;$('#expired').hidden=false;$('#timer').textContent='00:00'}
async function refresh(){try{state=await api('/api/state');selected=Math.max(0,Math.min(4,state.selected??selected));header();problem();clearInterval(timer);const tick=()=>{const s=Math.max(0,state.expiresAt-Math.floor(Date.now()/1000));$('#timer').textContent=fmt(s);if(s<=0)expire()};tick();timer=setInterval(tick,1000)}catch(e){if(e.status===410)expire();else result({compile:{ok:false,message:e.message}})}}
async function save(show=true){if(!state)return;const code=$('#code').value;$('#saveState').textContent='Saving…';try{await api('/api/save','POST',{index:selected,code});dirty=false;$('#saveState').textContent='Saved on disk';if(show)$('#result').textContent='Saved. Run this exact version to earn PASS.';await refresh()}catch(e){$('#saveState').textContent='Save failed';$('#result').className='bad';$('#result').textContent=e.message}}
async function run(){const code=$('#code').value;$('#run').disabled=$('#save').disabled=true;$('#result').textContent='Compiling and running hidden tests…';try{const r=await api('/api/run','POST',{index:selected,code});dirty=false;await refresh();result(r)}catch(e){if(e.status===410)expire();else{$('#result').className='bad';$('#result').textContent=e.message}}finally{$('#run').disabled=$('#save').disabled=false}}
async function action(kind){try{await api('/api/action','POST',{action:kind});$('#result').className='good';$('#result').textContent=kind==='maintenance'?'macOS authorization opened. After final re-check, maintenance lasts 10 minutes.':'macOS authorization opened. Final re-check must pass before uninstall.'}catch(e){$('#result').className='bad';$('#result').textContent=e.message}}
let autosave;$('#code').addEventListener('input',()=>{dirty=true;$('#saveState').textContent='Unsaved changes';clearTimeout(autosave);autosave=setTimeout(()=>save(false),800)});$('#code').addEventListener('keydown',e=>{if(e.key==='Tab'){e.preventDefault();const t=e.target,a=t.selectionStart,b=t.selectionEnd;t.value=t.value.slice(0,a)+'    '+t.value.slice(b);t.selectionStart=t.selectionEnd=a+4;t.dispatchEvent(new Event('input'))}if((e.metaKey||e.ctrlKey)&&e.key==='Enter'){e.preventDefault();run()}});$('#save').onclick=()=>save(true);$('#run').onclick=run;$('#maintenance').onclick=()=>action('maintenance');$('#uninstall').onclick=()=>action('uninstall');$('#reload').onclick=()=>location.reload();refresh()})();
